### ISSUE TITLE
连接到6w报错“Too many connections”

### ISSUE THREAD

**Issue by AllMyPrecious** [wildfirechat/C1000K_Test#2]
连接到6w多的时候，IM-Server报错“Too many connection”，我想知道是不是和我mysql的配置有关系。

**Comment by imndx** [comment]
这部分[配置优化](https://github.com/wildfirechat/C1000K_Test#%E4%BC%98%E5%8C%96im%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE)都做了吗？

**Comment by AllMyPrecious** [comment]
是的，已经是做过了，每次就会在64508的链接后报错，无法再建立连接

**Comment by imndx** [comment]
贴个报错截图看下

**Comment by AllMyPrecious** [comment]
![06a1ca197f5c405674a9d5b4d3cecec](https://github.com/wildfirechat/C1000K_Test/assets/44085110/ed34a522-0d40-47bf-ac2d-95dbc85da872)

**Comment by heavyrain2012** [comment]
单个电脑最多有65535个端口，每建立一个连接都会占用一个端口，所以只能连6W+是正常的。如果要测试百万连接，可以找多台电脑。比如我们自己测试，用了20台，每台连5W，总计100万

**Comment by AllMyPrecious** [comment]
是的，我忘了这茬了
